version: '3'
services:
    lodex-workers-saxon:
        container_name: lodex-workers-saxon
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/lodex-workers-saxon:1.1.0
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
